language: python
os:
  - linux
  - osx

python:
  - "3.5"

install:
  - pip install virtualenv
  - pip install virtualenvwrapper
  - npm install -g bower

script:
  - ". virtualenvwrapper.sh"
  - mkvirtualenv project-name
  - pip install invoke
  - inv init
