language: python
os:
  - linux
  - osx

python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py check

