language: python
python:
  - "3.4"
  - "2.7"

install:
  - pip install virtualenv
  - pip install fabric

script: 
  - python init_project_stub.py
  - python helpers/mkfolders.py
  - python helpers/mkvirtualenv.py
